# Generated by Django 5.2.4 on 2026-09-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_caseassignment_reject_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiverequest',
            name='admin_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detectiverequest',
            name='requested_detective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detective_request_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectiverequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
