# Generated by Django 5.2.4 on 2026-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_id_proof_profile_verification_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complaint_number',
            field=models.CharField(default='', help_text='Police station complaint registered number', max_length=100),
        ),
    ]
