# Generated by Django 5.2.4 on 2026-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_case_complaint_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='complaint_number',
            field=models.CharField(blank=True, default='', help_text='Police station complaint registered number (LOST cases only)', max_length=100),
        ),
    ]
