# Generated by Django 5.2.4 on 2026-09-17 17:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_casesolverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(default=app.models.case_no, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('ITEM', 'Item'), ('PET', 'Pet'), ('PERSON', 'Person')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='case',
            name='complaint_number',
            field=models.CharField(blank=True, default='', help_text='Police station complaint registered number (LOST cases only)', max_length=40),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='case',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('FOUND', 'Found'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='faiss_vector_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to='case_images/'),
        ),
        migrations.AlterField(
            model_name='casesolverequest',
            name='previous_status',
            field=models.CharField(default='OPEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='casesolverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='detectiveachievement',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='detectiveachievement',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='detectiverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='investigationupdate',
            name='evidence_photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='investigationupdate',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='detective_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_proof',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='sightings/'),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='reporter_contact',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
