# Generated by Django 5.2.4 on 2026-09-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blog_image_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('ITEM', 'Item'), ('PET', 'Pet'), ('PERSON', 'Person')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='case',
            name='complaint_number',
            field=models.CharField(blank=True, default='', help_text='Police station complaint registered number (LOST cases only)', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('FOUND', 'Found'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=13),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=9),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='faiss_vector_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casesolverequest',
            name='previous_status',
            field=models.CharField(default='OPEN', max_length=13),
        ),
        migrations.AlterField(
            model_name='casesolverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='detectiveachievement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detectiverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='investigationupdate',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigationupdate',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='detective_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='reporter_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
